# Run Orfeo Toolbox in a container
#
# one of the following two lines can be used below to select
# which repository to use.
# the 1st has otb version 5.4.0
# the 2nd has otb version 5.8.0
# the 3rd has otb version 6.0
#
#        add-apt-repository ppa:ubuntugis/ppa &&\
#        add-apt-repository ppa:ubuntugis/ubuntugis-unstable &&\
#        add-apt-repository ppa:ubuntugis/ubuntugis-experimental &&\
#

FROM ubuntu:16.04
MAINTAINER Stephen Woodbridge <woodbri@imaptools.com>

RUN apt-get -qqy update &&\
        apt-get -qqy install software-properties-common &&\
        apt-get -qqy update &&\
        add-apt-repository ppa:ubuntugis/ubuntugis-unstable &&\
        apt-get -qqy update &&\
        apt-get -qqy install \
          gdal-bin \
          imagemagick \
          libotb \
          libterm-readline-perl-perl \
          locales-all \
          otb-bin \
          otb-bin-qt \
          sudo \
          vim \
          wget \
          && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*


ENTRYPOINT
CMD ["/bin/bash"]
